//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrafikLekarzy
    {
        public int GrafikID { get; set; }
        public Nullable<int> LekarzID { get; set; }
        public Nullable<System.DateTime> DataPoczatku { get; set; }
        public Nullable<System.DateTime> DataKonca { get; set; }
    
        public virtual Lekarze Lekarze { get; set; }
    }
}
