//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoriaChorob
    {
        public int HistoriaID { get; set; }
        public Nullable<int> PacjentID { get; set; }
        public Nullable<int> ChorobaID { get; set; }
        public Nullable<System.DateTime> DataDiagnozy { get; set; }
        public Nullable<System.DateTime> DataWyleczenia { get; set; }
    
        public virtual Choroby Choroby { get; set; }
        public virtual Pacjenci Pacjenci { get; set; }
    }
}
