//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class przychodniaEntities : DbContext
    {
        public przychodniaEntities()
            : base("name=przychodniaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Choroby> Choroby { get; set; }
        public virtual DbSet<GrafikLekarzy> GrafikLekarzy { get; set; }
        public virtual DbSet<HarmonogramZabiegow> HarmonogramZabiegow { get; set; }
        public virtual DbSet<HistoriaChorob> HistoriaChorob { get; set; }
        public virtual DbSet<Lekarze> Lekarze { get; set; }
        public virtual DbSet<Leki> Leki { get; set; }
        public virtual DbSet<Pacjenci> Pacjenci { get; set; }
        public virtual DbSet<Platnosci> Platnosci { get; set; }
        public virtual DbSet<Pokoje> Pokoje { get; set; }
        public virtual DbSet<Recepcjonisci> Recepcjonisci { get; set; }
        public virtual DbSet<Recepty> Recepty { get; set; }
        public virtual DbSet<Specjalizacje> Specjalizacje { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<SzczegolyRecept> SzczegolyRecept { get; set; }
        public virtual DbSet<Wizyty> Wizyty { get; set; }
        public virtual DbSet<Zabiegi> Zabiegi { get; set; }
    }
}
