//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SzczegolyRecept
    {
        public int SzczegolyID { get; set; }
        public Nullable<int> ReceptaID { get; set; }
        public Nullable<int> LekID { get; set; }
        public Nullable<int> Ilosc { get; set; }
    
        public virtual Leki Leki { get; set; }
        public virtual Recepty Recepty { get; set; }
    }
}
