//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wizyty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Wizyty()
        {
            this.Platnosci = new HashSet<Platnosci>();
        }
    
        public int WizytaID { get; set; }
        public Nullable<int> PacjentID { get; set; }
        public Nullable<int> LekarzID { get; set; }
        public Nullable<System.DateTime> DataWizyty { get; set; }
        public string Notatka { get; set; }
        public string Status { get; set; }
    
        public virtual Lekarze Lekarze { get; set; }
        public virtual Pacjenci Pacjenci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Platnosci> Platnosci { get; set; }
    }
}
